name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

x-ubuntu-version: &ubuntu_version ubuntu-24.04
x-windows-version: &windows_version windows-2022
x-php-version: &php_version '8.4'

env:
  PHP_VERSION: *php_version

jobs:
  testsuite:
    name: Testsuite
    runs-on: *ubuntu_version
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.4']

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          ini-values: zend.assertions = 1

      - name: Composer install
        uses: ramsey/composer-install@v3

      - name: Run PHPUnit (no coverage)
        if: ${{ matrix.php-version != env.PHP_VERSION }}
        run: vendor/bin/phpunit --display-deprecations --display-warnings

      - name: Run PHPUnit (with coverage)
        if: ${{ matrix.php-version == env.PHP_VERSION }}
        run: vendor/bin/phpunit --display-deprecations --display-warnings --log-junit junit.xml --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        if: ${{ matrix.php-version == env.PHP_VERSION }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ matrix.php-version == env.PHP_VERSION }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: *ubuntu_version

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          tools: cs2pr

      - name: Composer install
        uses: ramsey/composer-install@v3

      - name: Run PHP CodeSniffer
        continue-on-error: true
        run: vendor/bin/phpcs --report-full --report-checkstyle=./phpcs-report.xml

      - name: Show PHPCS results in PR
        run: cs2pr ./phpcs-report.xml

      - name: Run phpstan
        run: vendor/bin/phpstan analyse --error-format=github

  testsuite-windows:
    runs-on: *windows_version
    name: Windows Testsuite

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: intl, mbstring, pdo_sqlite
          ini-values: apc.enable_cli = 1

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run test suite
        run: vendor/bin/phpunit --display-deprecations --display-warnings
